services:
  chatapp_local:
    container_name: chatapp_local
    image: chatapp_local
    build:
      context: ../../
      dockerfile: docker/local/chatapp/Dockerfile
    volumes:
      - ../../src:/app/src
      - ../../public:/app/public
    restart: always
    ports:
      - 3000:3000
  nginx_local:
    container_name: nginx_local
    image: nginx_local
    build:
      context: ../../
      dockerfile: docker/local/nginx/Dockerfile
    restart: always
    depends_on:
      - chatapp_local
    ports:
      - 80:80
