services:
  chatapp:
    container_name: chatapp
    build:
      context: ../../
      dockerfile: docker/local/Dockerfile
    volumes:
      - ../../src:/app/src
      - ../../public:/app/public
    restart: always
    ports:
      - 3000:3000
