services:
  chatapp_develop:
    container_name: chatapp_develop
    image: chatapp_develop
    build:
      context: ../../
      dockerfile: docker/develop/chatapp/Dockerfile
    restart: always
    ports:
      - 3000:3000
  nginx_develop:
    container_name: nginx_develop
    image: nginx_develop
    build:
      context: ../../
      dockerfile: docker/develop/nginx/Dockerfile
    restart: always
    depends_on:
      - chatapp_develop
    ports:
      - 80:80
