services:
  chatapp:
    container_name: chatapp_develop
    image: chatapp_develop
    build:
      context: ../../
      dockerfile: docker/develop/Dockerfile
    restart: always
    ports:
      - 3000:3000
